services:
  godoc:
    build:
      context: .
      target: godoc
    ports:
      - 6060
    volumes:
      - type: bind
        source: .
        target: /usr/local/go/src/github.com/hiroara/carbo

  # Tools
  protoc:
    build:
      context: .
      target: protoc
    profiles:
      - tool
    volumes:
      - type: bind
        source: .
        target: /usr/local/go/src/github.com/hiroara/carbo
    command:
      - protoc
      - --go_out=internal/messaging/pb
      - --go_opt=paths=source_relative
      - --go-grpc_out=internal/messaging/pb
      - --go-grpc_opt=paths=source_relative
      - --proto_path=./proto
      - communicator.proto
      - message.proto
  toolkit:
    build:
      context: .
      target: toolkit
    profiles:
      - tool
    volumes:
      - type: bind
        source: .
        target: /usr/local/go/src/github.com/hiroara/carbo
