services:
  protoc:
    build:
      context: .
      target: protoc
    volumes:
      - type: bind
        source: .
        target: /work
    command:
      - protoc
      - --go_out=pb
      - --go_opt=paths=source_relative
      - --go-grpc_out=pb
      - --go-grpc_opt=paths=source_relative
      - --proto_path=./proto
      - communicator.proto
      - message.proto
