// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: communicator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchPullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *BatchPullRequest) Reset() {
	*x = BatchPullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPullRequest) ProtoMessage() {}

func (x *BatchPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPullRequest.ProtoReflect.Descriptor instead.
func (*BatchPullRequest) Descriptor() ([]byte, []int) {
	return file_communicator_proto_rawDescGZIP(), []int{0}
}

func (x *BatchPullRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BatchPullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BatchPullResponse) Reset() {
	*x = BatchPullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchPullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPullResponse) ProtoMessage() {}

func (x *BatchPullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPullResponse.ProtoReflect.Descriptor instead.
func (*BatchPullResponse) Descriptor() ([]byte, []int) {
	return file_communicator_proto_rawDescGZIP(), []int{1}
}

var File_communicator_proto protoreflect.FileDescriptor

var file_communicator_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x75, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x13,
	0x0a, 0x11, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x44, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x34, 0x0a, 0x09, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x75, 0x6c, 0x6c,
	0x12, 0x11, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x75, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x72, 0x6f, 0x61, 0x72, 0x61, 0x2f,
	0x63, 0x61, 0x72, 0x62, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_communicator_proto_rawDescOnce sync.Once
	file_communicator_proto_rawDescData = file_communicator_proto_rawDesc
)

func file_communicator_proto_rawDescGZIP() []byte {
	file_communicator_proto_rawDescOnce.Do(func() {
		file_communicator_proto_rawDescData = protoimpl.X.CompressGZIP(file_communicator_proto_rawDescData)
	})
	return file_communicator_proto_rawDescData
}

var file_communicator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_communicator_proto_goTypes = []interface{}{
	(*BatchPullRequest)(nil),  // 0: BatchPullRequest
	(*BatchPullResponse)(nil), // 1: BatchPullResponse
}
var file_communicator_proto_depIdxs = []int32{
	0, // 0: Communicator.BatchPull:input_type -> BatchPullRequest
	1, // 1: Communicator.BatchPull:output_type -> BatchPullResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_communicator_proto_init() }
func file_communicator_proto_init() {
	if File_communicator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_communicator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchPullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchPullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_communicator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communicator_proto_goTypes,
		DependencyIndexes: file_communicator_proto_depIdxs,
		MessageInfos:      file_communicator_proto_msgTypes,
	}.Build()
	File_communicator_proto = out.File
	file_communicator_proto_rawDesc = nil
	file_communicator_proto_goTypes = nil
	file_communicator_proto_depIdxs = nil
}
